### ISSUE TITLE
white background in gvim

### ISSUE THREAD

**Issue by wedgwood** [tassmjau/vim-mwnochrome#1]
After update to latest version, `mwnochrome` seems no dark background in gvim.

**Comment by tassmjau** [comment]
oh, I wasn't aware anyone else than me was using this theme :)
I can have a look at gvim, though I suspect things are horribly broken there, since I've only ever used this in urxvt/xterm, ie only with cterm colors....

**Comment by tassmjau** [comment]
https://github.com/tassmjau/vim-mwnochrome/commit/0a7ddb8b8f3077327c80aa746a333ac2b22f2c29 <-- this should fix the gvim-background.
